server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/vasilevskiy

logging:
  level:
    ru.kc4kt4: debug
    com: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: app.log